# Generated by Django 4.2 on 2023-10-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Police',
            fields=[
                ('police_id', models.IntegerField(primary_key=True, serialize=False)),
                ('police_name', models.CharField(max_length=20)),
                ('police_rank', models.CharField(max_length=20)),
                ('police_email', models.EmailField(max_length=20)),
                ('police_phone_number', models.IntegerField(max_length=20)),
            ],
        ),
    ]
