# Generated by Django 4.2 on 2023-11-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactenquiry', '0002_remove_contactenquiry_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactenquiry',
            name='first_name',
            field=models.CharField(max_length=20),
        ),
    ]
