# Generated by Django 4.2 on 2023-10-11 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('firReport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('update_id', models.IntegerField(primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=100)),
                ('update_description', models.CharField(max_length=300)),
                ('update_time', models.DateTimeField(max_length=20)),
                ('report_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firReport.firreport')),
            ],
        ),
    ]
