# Generated by Django 4.2 on 2023-10-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('supervisor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('supervisor_name', models.CharField(max_length=20)),
                ('supervisor_phone_number', models.IntegerField(max_length=20)),
                ('supervisor_email', models.EmailField(max_length=20)),
            ],
        ),
    ]
