# Generated by Django 4.2 on 2023-10-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=20)),
                ('user_email', models.EmailField(max_length=20)),
                ('user_password', models.CharField(max_length=20)),
                ('user_phone_number', models.IntegerField(max_length=20)),
                ('user_address', models.CharField(max_length=20)),
            ],
        ),
    ]
