# Generated by Django 4.2 on 2023-10-11 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crimerecord',
            fields=[
                ('record_id', models.IntegerField(primary_key=True, serialize=False)),
                ('crime_type', models.CharField(max_length=20)),
                ('crime_description', models.CharField(max_length=500)),
                ('crime_time', models.DateTimeField(max_length=20)),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.location')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
